version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t vault-note-image:latest -f Dockerfile.backend .
      - docker tag vault-note-image:latest amar0898/vault-note:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push amar0898/vault-note:latest
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'